services:
#  mysql:
#    image: "mysql:8.0.39"
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=041212
#      - MYSQL_DATABASE=E-commerce
#  redis:
#    image: "redis:7.0.15"
#    ports:
#      - "6379:6379"
  consul:
    image: "hashicorp/consul:1.15.4"
    ports:
      - "8500:8500"
  # Jaeger
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
#  etcd:
#    image: docker.io/bitnami/etcd:3.5
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#    ports:
#      - 2379:2379
#      - 2380:2380
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
#
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - ./app/frontend/log:/logs/frontend
    command: -config.file=/etc/promtail/config.yml

#  frontend:
##    image: e-commerce-frontend:latest
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.frontend
#    ports:
#      - "8080:8080"
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - SESSION_SECRET=041212
#      - GO_ENV=dev
#    depends_on:
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/frontend/conf/dev:/opt/E-commerce/frontend/conf/dev
#
#  product:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=product
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=041212
#      - MYSQL_HOST=154.37.220.49
#      - GO_ENV=dev
#    depends_on:
#      frontend:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/product/conf/dev:/opt/E-commerce/product/conf/dev
#
#  user:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=user
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=041212
#      - MYSQL_HOST=154.37.220.49
#      - GO_ENV=dev
#    depends_on:
#      product:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/user/conf/dev:/opt/E-commerce/user/conf/dev
#
#  cart:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=cart
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=041212
#      - MYSQL_HOST=154.37.220.49
#      - GO_ENV=dev
#    depends_on:
#      user:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/cart/conf/dev:/opt/E-commerce/cart/conf/dev
#
#  order:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=order
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=041212
#      - MYSQL_HOST=154.37.220.49
#      - GO_ENV=dev
#    depends_on:
#      cart:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/order/conf/dev:/opt/E-commerce/order/conf/dev
#
#  payment:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=payment
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=041212
#      - MYSQL_HOST=154.37.220.49
#      - GO_ENV=dev
#    depends_on:
#      order:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/payment/conf/dev:/opt/E-commerce/payment/conf/dev
#
#  checkout:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=checkout
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=041212
#      - MYSQL_HOST=154.37.220.49
#      - GO_ENV=dev
#    depends_on:
#      payment:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/checkout/conf/dev:/opt/E-commerce/checkout/conf/dev
#
#  email:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=email
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=041212
#      - MYSQL_HOST=154.37.220.49
#      - GO_ENV=dev
#    depends_on:
#      checkout:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/email/conf/dev:/opt/E-commerce/email/conf/dev
#
#  casbin:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=casbin
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
#      - OTEL_EXPORTER_OTLP_INSECURE=true
#      - GO_ENV=dev
#    depends_on:
#      email:
#        condition: service_started
#      consul:
#        condition: service_started
#    volumes:
#      - ./app/casbin/conf/dev:/opt/E-commerce/casbin/conf/dev
